In [ ]:
import numpy as np
from numpy import loadtxt
from xgboost import XGBClassifier,XGBRegressor
from xgboost import plot_importance
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score,mean_squared_error
from sklearn.model_selection import cross_validate   #Additional scklearn functions
from sklearn.model_selection import learning_curve, GridSearchCV #Perforing grid search
from sklearn.metrics import confusion_matrix

import matplotlib.pyplot as plt 
import pandas as pd
from matplotlib import pyplot

In [1]:
data = pd.read_csv('C:/Users/rajat.sinha/Downloads/XXXX/APPF_dataset_v2.csv')
data.head()


NameError: name 'pd' is not defined

In [3]:
#data = data[data['Ranks']<=500]
data.shape


(63271, 82)

In [2]:
feature_cols = data.columns[4:74]
print(feature_cols)
X = pd.DataFrame(data.iloc[:,5:73])
y = pd.DataFrame(data.iloc[:,73])


NameError: name 'data' is not defined

In [3]:
print(y)
print(X.head())




NameError: name 'y' is not defined

In [4]:
#mergedata = data.append(X)
#testcount = len(testdata)
#count = len(mergedata)-testcount
X_cat = X.copy()

X_cat = X.select_dtypes(include=['object'])
X_enc = X_cat.copy()


X_enc = pd.get_dummies(X_enc)
X_enc


NameError: name 'X' is not defined

In [5]:
mergedata = X.drop(['XXXX'],axis=1)
X
mergedata

NameError: name 'X' is not defined

In [ ]:
X = pd.concat([mergedata,X_enc], axis=1)
X

In [6]:
# split data into train and test sets
seed = 11
test_size = 0.30
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=test_size, random_state=seed)
#print X_train.shape, y_train.shape
#print X_test.shape, y_test.shape

NameError: name 'train_test_split' is not defined

In [9]:
#feature scaling
from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()
X_train = sc_X.fit_transform(X_train)
X_test = sc_X.transform(X_test)


In [ ]:
# Necessary imports: 
from sklearn.model_selection import cross_val_score, cross_val_predict
from sklearn import metrics


In [ ]:
# fit model no training data
model = XGBRegressor()

In [ ]:
model.fit(X_train, y_train)



In [ ]:
print(model.feature_importances_)
pd.DataFrame(model.feature_importances_, index=X.columns, 
             columns=['Importance']).sort_values('Importance',ascending=False)

(pd.Series(model.feature_importances_,index=X.columns).sort_values(ascending=False).nlargest(20).plot(kind='barh'))


In [ ]:
pip install pandas-profiling

In [ ]:
from pandas_profiling import ProfileReport

In [ ]:
prof = ProfileReport(data,minimal=True)
prof
prof.to_file(output_file='eda.html')

In [ ]:
# make predictions for test data
y_pred = model.predict(X_test)
predictions = [round(value) for value in y_pred]


In [ ]:
pd.scatter

In [ ]:
# evaluate predictions
accuracy = accuracy_score(y_test, predictions)
print("Accuracy: %.2f%%" % (accuracy * 100.0))

In [ ]:
mean_squared_error(y_test, predictions)

y_test.mean()


XGb-Classifier 

In [ ]:
y['RPO'].quantile([0,0.25,0.5,0.75,1])

In [ ]:
y 


In [6]:
y['RPO_Quart']=y['RPO'].map(lambda x: 'Q4' if x >= 58  else 'Q3' if x >= 42 else 'Q2' if x >= 32 else 'Q1'  ) # if  'Q2' )
y['RPO_Quart'].unique()
y
#y.drop(['Flag'],axis=1)


RPO RPO_Quart
0      577.0        Q4
1      564.0        Q4
2      545.0        Q4
3      538.0        Q4
4      490.0        Q4
...      ...       ...
63266    0.0        Q1
63267    0.0        Q1
63268    0.0        Q1
63269    0.0        Q1
63270    0.0        Q1

[63271 rows x 2 columns]

In [7]:
y = y.drop(['RPO'],axis=1)
y


RPO_Quart
0            Q4
1            Q4
2            Q4
3            Q4
4            Q4
...         ...
63266        Q1
63267        Q1
63268        Q1
63269        Q1
63270        Q1

[63271 rows x 1 columns]

In [10]:
# fit model no training data
model = XGBClassifier()


In [11]:
model.fit(X_train, y_train)


C:\Users\rajat.sinha\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\preprocessing\label.py:219: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\rajat.sinha\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\preprocessing\label.py:252: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, gamma=0,
              learning_rate=0.1, max_delta_step=0, max_depth=3,
              min_child_weight=1, missing=None, n_estimators=100, n_jobs=1,
              nthread=None, objective='multi:softprob', random_state=0,
              reg_alpha=0, reg_lambda=1, scale_pos_weight=1, seed=None,
              silent=None, subsample=1, verbosity=1)

In [7]:
#Model Features Importance
print(model.feature_importances_)
pd.DataFrame(model.feature_importances_, index=X.columns, 
             columns=['Importance']).sort_values('Importance',ascending=False)

(pd.Series(model.feature_importances_,index=X.columns).sort_values(ascending=False).nlargest(20).plot(kind='barh'))


NameError: name 'model' is not defined

In [13]:
# make predictions for test data
y_pred = model.predict(X_test)
predictions = [(value) for value in y_pred]


In [14]:
# evaluate predictions
accuracy = accuracy_score(y_test, predictions)
print("Accuracy: %.2f%%" % (accuracy * 100.0))

Accuracy: 78.50%


In [15]:
#Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)

print(cm)

[[3747  866   70    8]
 [ 495 3040  853   31]
 [  23  632 3668  595]
 [   0    7  501 4446]]


In [19]:
model.predict_proba(X_test)

array([[0.53254235, 0.45205498, 0.01417119, 0.00123144],
       [0.0076856 , 0.01938817, 0.08538451, 0.88754165],
       [0.06638932, 0.5880676 , 0.342975  , 0.00256813],
       ...,
       [0.00603118, 0.02128279, 0.2268257 , 0.74586034],
       [0.15622935, 0.39027414, 0.3260547 , 0.12744181],
       [0.00782267, 0.01671189, 0.20339802, 0.77206737]], dtype=float32)

In [ ]:
#Final_answer
